mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(
        redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('api/token/', TokenObtainPairView.as_view(),
         name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),
    path('api/token/refresh/', TokenRefreshView.as_view(),
         name='token_refresh'),
    path('task_tracker/', include('task_tracker.urls',
                                  namespace='task_tracker')),
    path('api/task_tracker/', include('task_tracker.api.urls',
                                      namespace='api_task_tracker')),
]

task_tracker/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views
app_name = 'task_tracker_api'

router = routers.DefaultRouter()
router.register('tasks', views.TaskViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

task_tracker/urls.py
from django.urls import path
from . import views
app_name = 'task_tracker'


urlpatterns = [
    path('task/list', views.TaskListView.as_view(),
         name="task_list"),
    path('task/create', views.TaskCreateView.as_view(), name="task_create"),
    path('task/<int:pk>/update', views.TaskUpdateView.as_view(),
         name="task_update"),
]

task_tracker/models.py
from django.db import models
from django.conf import settings

STATUS_CHOICES = (
    (0, "Планируется"),
    (1, "Активная"),
    (2, "Контроль"),
    (3, "Завершена")
)


# Базовый абстрактный класс
class ItemBase(models.Model):
    title = models.CharField(max_length=180)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


# Задача
class Task(ItemBase):
    description = models.TextField()
    performer = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='performer_tasks')
    observers = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name='observers_tasks')
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    start_date = models.DateField()
    start_time = models.TimeField()
    end_date = models.DateField()
    end_time = models.TimeField()
    planned_end_date = models.DateField(null=True, blank=True)
    planned_end_time = models.TimeField(null=True, blank=True)


# Чек лист задачи
class TaskChekList(ItemBase):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    is_completed = models.BooleanField(default=False)


# Изменение статуса
class StatusChange(models.Model):
    previous_status = models.IntegerField(choices=STATUS_CHOICES)
    next_status = models.IntegerField(choices=STATUS_CHOICES)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


# Напоминание
class Reminder(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    description = models.TextField()
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)

task_tracker/forms.py
from django import forms
from .models import Task


# Форма задачи
class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = [
            'title', 'description', 'performer',
            'observers', 'start_date', 'start_time',
            'end_date', 'end_time', 'status',
            'planned_end_date', 'planned_end_time',
        ]

task_tracker/api/views.py
from rest_framework import viewsets
from .serializers import TaskSerializer
from ..models import Task


# Task list, retrieve, create ,update api
class TaskViewSet(viewsets.ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

task_tracker/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.forms.models import inlineformset_factory
from .models import Task, TaskChekList
from .forms import TaskForm


# Список задач
class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'task_tracker/task/list.html'
    model = Task
    context_object_name = 'tasks'


# Mixin задачи
class TaskEditMixin(LoginRequiredMixin):
    template_name = 'task_tracker/task/form.html'
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('task_tracker:task_list')

    # formset
    def __get_task_formset(self, data=None):
        TaskFormSet = inlineformset_factory(
            Task,
            TaskChekList,
            fields=['title', 'is_completed'],
            extra=1, can_delete=True)
        return TaskFormSet(
            instance=self.object, data=data)

    def form_valid(self, form):
        task_formset = self.__get_task_formset(
            data=self.request.POST)
        if task_formset.is_valid():
            task_checklists = task_formset.save(
                commit=False
            )
            for task_checklist in task_checklists:
                task_checklist.task = form.instance
                task_checklist.save()
            task_deleted_objects = task_formset.deleted_objects
            for task_deleted in task_deleted_objects:
                task_deleted.delete()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_formset'] = self.__get_task_formset()
        return context


# Создание задачи
class TaskCreateView(TaskEditMixin, CreateView):
    pass


# Обновление задачи
class TaskUpdateView(TaskEditMixin, UpdateView):
    pass

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <title>Трекер задач</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src="{% static 'js/formset.js' %}"></script>
</head>
<body>
  <nav class="navbar navbar-expand-sm bg-default navbar-default">
    <!-- Brand/logo -->
    <a class="navbar-brand" href="#">Трекер задач</a>
    <a href="{% url 'logout' %}" class="pull-right">Выход</a>
  </nav>
  <br><br>
  <div class="container">
    {% block content %}{% endblock %}
    {% block modal %}{% endblock %}
  </div>
</body>
</html>

templates/task_tracker/task/form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block content %}
<form method="POST" action="">
	{% csrf_token %}
	<h3>Добавить новую задачу </h3>

	название <br> 
	{{ form.title }} <br>
	Описание <br> 
	{{ form.description }} <br>
	исполнитель <br> 
	{{ form.performer }} <br>
	наблюдатели <br> 
	{{ form.observers }} <br>
	статус <br>: 
	{{ form.status }} <br>
	Дата и время начала: <br> 
	{{ form.start_date|attr:"type:date" }}<br>
	{{ form.start_time|attr:"type:time" }} <br>
	Дата и время завершения: <br>
	{{ form.end_date|attr:"type:date" }}<br>
	{{ form.end_time|attr:"type:time" }} <br>
	планируемое дата и время завершения:<br>
	{{ form.planned_end_date|attr:"type:date" }}<br>
	{{ form.planned_end_time|attr:"type:time" }} <br>
	<div class="form-group formset">
		{{ task_formset.management_form }}
	    <label for="email">Чек лист: </label> <button class="btn-sm btn-primary add-inline-form">+</button><br>
	    <div class="formset-forms">
            {% for task_checklist in task_formset %}
              <div class="form-group formset-form">
                {% for hidden in task_checklist.hidden_fields %}
                  {{ hidden }}
                {% endfor %}
                {{ task_checklist.title }}
                {{ task_checklist.is_completed }}
                {{ task_checklist.DELETE }}
              </div>
            {% endfor %}
          </div>
          <div class="form-group empty-form d-none">
              {{ task_formset.empty_form.title }}
              {{ task_formset.empty_form.is_completed }}
              {{ task_formset.empty_form.DELETE }}
            </div>
          </div>
	</div><br>
	<input type="submit" class="btn btn-success" name="" value="Сохранить"><br><br>
</form>
{% endblock %}

templates/task_tracker/task/list.html
{% extends "base.html" %}
{% load task_tracker_tags %}
{% block content %}
  <h3 style="display: inline;">Список задач </h3>
  <a href="{% url 'task_tracker:task_create' %}" class="btn btn-success pull-right" style="float: right;">+ Добавить новую задачу</a><br><br>
  
  <table class="table table-bordered">
    <tr>
      <th>Название</th>
      <th>Описание</th>
      <th>Исполнитель</th>
      <th>Наблюдатели</th>
      <th>Статус</th>
      <th>Время начала</th>
      <th>Время завершения</th>
      <th>Планируемое время завершения</th>
      <th>Чек лист</th>
    </tr>
    {% for task in tasks %}
      <tr>
        <td>{{ task.title }}</td>
        <td>{{ task.description }}</td>
        <td>{{ task.performer.get_full_name }}</td>
        <td>
          {% for observer in task.observers.all %}
            {{ observer.get_full_name }} <br>
          {% endfor %}
        </td>
        <td>{{ task.get_status_display }}</td> 
        <td>{{ task.start_datetime|date:'d.m.Y H:i' }}</td>
        <td>{{ task.end_datetime|date:'d.m.Y H:i' }}</td>
        <td>{{ task.planned_end_datetime|date:'d.m.Y H:i' }}</td>
        <td>
          {% for taskcheklist in task.taskcheklist_set.all %}
            {{ taskcheklist.title }}
            {% if taskcheklist.is_completed %}
              [Выполнен]
            {% else %}
              [Не выполнен]
            {% endif %}
          {% empty %}
            ----
          {% endfor %}
        </td>
        <td>
          {% is_expired task.end_datetime as is_expired %}
          {% if is_expired %}
              <span style="color: red;">Просрочена</span>
          {% endif %}
          <a href="{% url 'task_tracker:task_update' pk=task.id %}">Обновить</a>
        </td>

      </tr>
    {% endfor %}
  </table>
{% endblock %}